# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

os:
  - linux
    r:
    - release
    - devel
  - os: osx
    osx_image: xcode7.3
    disable_homebrew: true
    r: release
    r_build_args: '--no-build-vignettes'
    r_check_args: '--ignore-vignettes --no-examples'



r-packages:
  - reticulate
  - igraph
  - RColorBrewer

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - chmod +x travis_setup.sh
  - ./travis_setup.sh

before_install:
  - sudo apt-get update; sudo apt-get install -y libpython-dev; sudo apt-get install -y libpython3-dev
  - sudo apt-get install -y texlive-full
  - pip install --user igraph
  - pip install --user numpy
  - pip install --user leidenalg

warnings_are_errors: false
