# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

matrix:
  include:
    - os: linux
    - os: osx

    #osx_image: xcode10.1
    #disable_homebrew: true
    #r_build_args: '--no-build-vignettes'
    #r_check_args: '--ignore-vignettes --no-examples'

addons:
  apt:
    #sources:
    #  - ubuntu-toolchain-r-test
    packages:
      - libpython-dev
      - libpython3-dev
      - texlive-full
      - cmake
      - python3
  #homebrew:
    #packages:
      #- libpython-dev
      #- libpython3-dev
      #- texlive-full
      #- cmake
      #- python3
    #update: true

matrix:
  include:
    - r: release
    - r: devel

r-packages:
  - reticulate
  - igraph
  - RColorBrewer

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --ignore-vignettes --no-examples"
    - R_BUILD_ARGS="--no-build-vignettes"

matrix:
  include:
    - os: linux
      r: release
      python: 2.7
      env: PYENV="py27"
    - os: linux
      r: release
      python: 3.5
      env: PYENV="py35"
    - os: linux
      r: release
      python: 3.6
      env: PYENV="py36"
    - os: linux
      r: release
      python: 3.7
      env: PYENV="py37"
    - os: linux
      r: release
      python: 3.8
      env: PYENV="py38"
    - os: osx
      r: release
      python: 2.7
      env: PYENV="py27"
    - os: osx
      r: release
      python: 3.5
      env: PYENV="py35"
    - os: osx
      r: release
      python: 3.6
      env: PYENV="py36"
    - os: osx
      r: release
      python: 3.7
      env: PYENV="py37"
    - os: osx
      r: release
      python: 3.8
      env: PYENV="py38"
    - os: linux
      r: devel
      python: 2.7
      env: PYENV="py27"
    - os: linux
      r: devel
      python: 3.5
      env: PYENV="py35"
    - os: linux
      r: devel
      python: 3.6
      env: PYENV="py36"
    - os: linux
      r: devel
      python: 3.7
      env: PYENV="py37"
    - os: linux
      r: devel
      python: 3.8
      env: PYENV="py38"
    - os: osx
      r: devel
      python: 2.7
      env: PYENV="py27"
    - os: osx
      r: devel
      python: 3.5
      env: PYENV="py35"
    - os: osx
      r: devel
      python: 3.6
      env: PYENV="py36"
    - os: osx
      r: devel
      python: 3.7
      env: PYENV="py37"
    - os: osx
      r: devel
      python: 3.8
      env: PYENV="py38"

before_install:
  - chmod +x travis_setup.sh
  - ./travis_setup.sh
  - pip install --user conda
  - pip install --user python-igraph
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user leidenalg

warnings_are_errors: false
