# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

os:
  - linux
  - osx

r:
  - release
  - devel

r-packages:
  - reticulate
  - igraph
  - RColorBrewer

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - chmod +x travis_setup.sh
  - ./travis_setup.sh

before_install:
  - apt-get update
  - apt-get install -y libpython-dev
  - apt-get install -y libpython3-dev
  - pip install --user igraph
  - pip install --user numpy
  - pip install --user leidenalg

warnings_are_errors: false
