# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r-packages:
  - reticulate

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - pip install --user igraph
  - pip install --user numpy
  - pip install --user leidenalg

