# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - linux
  - osx

r: release

r-packages:
  - reticulate
  - igraph
  - RColorBrewer

python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - chmod +x travis_setup.sh
  - ./travis_setup.sh

before_install:
  - pip install --user igraph
  - pip install --user numpy
  - pip install --user leidenalg

warnings_are_errors: false
