# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

python:
  - "2.7"
  - "3.6"
install:
  - pip install igraph
  - pip install leidenalg

