# DO NOT CHANGE the "init" and "install" sections below

image: Visual Studio 2015



environment:
  global:
    PATH: C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%
    R_ARCH: x64
    NOT_CRAN: true
    USE_RTOOLS: true
    _R_CHECK_FORCE_SUGGESTS_: false
  matrix:
    - PYTHON: "C:\\Python35"
      RETICULATE_PYTHON: "C:\\Python35"
      MINICONDA: C:\Miniconda3
    - PYTHON: "C:\\Python36"
      RETICULATE_PYTHON: "C:\\Python36"
      MINICONDA: C:\Miniconda3
    - PYTHON: "C:\\Python37"
      RETICULATE_PYTHON: "C:\\Python37"
      MINICONDA: C:\Miniconda3

matrix:
  fast_finish: true

# Download script file from GitHub
init:
  - ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
  - cmd: "ECHO %PYTHON_VERSION% %CONDA_INSTALL_LOCN%"

install:
  #install python libraries
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install --user python-igraph"
  - "%PYTHON%\\python.exe -m pip install --user igraph"
  - "%PYTHON%\\python.exe -m pip install --user numpy"
  - "%PYTHON%\\python.exe -m pip install --user leidenalg"
  - ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
